import addition, subtraction, multiplication, division
x = int(input("Enter first number: "))
y = int(input("Enter second number: "))
z=int(input("Enter third number: "))
u = (1, 2, 3)
add = addition.add_n(u)
add1=addition.add(x,y)
add2=addition.add2(x,y,z)
sub = subtraction.sub(x, y)
mul = multiplication.multiplication(*u)
div = division.div(x, y)
div2=division.floor_div(x,y)
div3=division.modulo(y,z)
print(type(u))
print(add)
print(add1)
print(add2)
print(sub)
print(mul)
print(div)
print(div2)
print(div3)